import type { Task } from "./task.type";
import { TASK_CATEGORY } from "./task.constant";

export const tasks: Task[] = [
  {
    id: 1,
    title: "Jogging",
    description: "Morning jog around the park for 30 minutes",
    category: TASK_CATEGORY.OUTDOOR,
    completed: false,
    dueDate: "2026-06-17",
    dueTime: "06:00",
  },
  {
    id: 2,
    title: "Reading",
    description: "Read a chapter of a programming book",
    category: TASK_CATEGORY.INDOOR,
    completed: false,
    dueDate: "2026-06-17",
    dueTime: "21:00",
  },
  {
    id: 3,
    title: "Gardening",
    description: "Water the plants and trim the bushes",
    category: TASK_CATEGORY.OUTDOOR,
    completed: true,
    dueDate: "2026-06-17",
    dueTime: "15:00",
  },
  {
    id: 4,
    title: "Cooking",
    description: "Prepare lunch for the family",
    category: TASK_CATEGORY.INDOOR,
    completed: true,
    dueDate: "2026-06-18",
    dueTime: "12:00",
  },
  {
    id: 5,
    title: "Cycling",
    description: "Ride a bike to the nearby lake",
    category: TASK_CATEGORY.OUTDOOR,
    completed: false,
    dueDate: "2026-06-21",
    dueTime: "06:00",
  },
  {
    id: 6,
    title: "Yoga",
    description: "Indoor yoga session for flexibility",
    category: TASK_CATEGORY.INDOOR,
    completed: false,
    dueDate: "2026-06-18",
    dueTime: "18:00",
  },
  {
    id: 7,
    title: "Photography",
    description: "Take photos at the botanical garden",
    category: TASK_CATEGORY.OUTDOOR,
    completed: false,
    dueDate: "2026-06-21",
    dueTime: "09:00",
  },
  {
    id: 8,
    title: "Clean Garage",
    description: "Organize and sweep the garage",
    category: TASK_CATEGORY.INDOOR,
    completed: false,
    dueDate: "2026-06-19",
    dueTime: "09:00",
  },
];
